language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-26.1.1
    - android-26
    - sys-img-armeabi-v7a-android-26
  licenses:
    - 'android-sdk-license-.+'
before_script:
  - yes | sdkmanager "platforms;android-26"
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: ./gradlew connectedAndroidTest